### ISSUE TITLE
Preview tab should scale to height of item

### ISSUE THREAD

**Issue by laurenrabaino** [voxmedia/autotune#114]
e.g. on a page like: http://staging.autotune.voxmedia.com/projects/basketball-table, the height of the preview is displaying at 150px:

![screen shot 2015-04-30 at 10 45 55 am](https://cloud.githubusercontent.com/assets/222285/7415329/2229aa04-ef26-11e4-8736-39a736fb7d1e.png)

and should be showing the full height of the embed, ~500px in this case:
![screen shot 2015-04-30 at 10 46 32 am](https://cloud.githubusercontent.com/assets/222285/7415342/33ddc9ba-ef26-11e4-80b0-7d9da5a58615.png)

**Comment by ryanmark** [comment]
This is a problem with the blueprint not initializing pym.js. If the preview doesn't resize, neither will the actual embed.
