### ISSUE TITLE
What is the difference between preview and view?

### ISSUE THREAD

**Issue by laurenrabaino** [voxmedia/autotune#116]
Can we remove one, or kill tlhem both since there's a preview option in the tab below?

**Comment by laurenrabaino** [comment]
![screen shot 2015-04-30 at 10 58 44 am](https://cloud.githubusercontent.com/assets/222285/7415631/3c8857cc-ef28-11e4-8dff-1cbaddb6be2c.png)

**Comment by ryanmark** [comment]
preview links you to the preview version, view links you to the published version.

**Comment by laurenrabaino** [comment]
can we rename to `Preview` and `View on site` ?

**Comment by laurenrabaino** [comment]
Or wait, what is the published version?

**Comment by ryanmark** [comment]
Whenever a project is saved or updated, it rebuilds and deploys a preview to a testing server. The preview is not meant to be distributed. The `preview` button links you to the copy on the testing server.
`Publishing` puts a copy of the project on a live server meant for public distribution and lots of traffic. `View` links you to this public copy.
