### ISSUE TITLE
Should we hide data / output tabs for projects? 

### ISSUE THREAD

**Issue by laurenrabaino** [voxmedia/autotune#117]
Seems like our primary users (editors/writers) would never use this and it should be deemphasized but available for developers who might want that data. 

![screen shot 2015-04-30 at 11 04 07 am](https://cloud.githubusercontent.com/assets/222285/7415720/c5ba74da-ef28-11e4-9f13-9c2fbfb9bb84.png)

**Comment by ryanmark** [comment]
These tabs should be hidden for editorial. We need permissions first (#35).
