### ISSUE TITLE
Can we call "build and publish" just "build"? 

### ISSUE THREAD

**Issue by laurenrabaino** [voxmedia/autotune#118]
Since publishing inherently requires a build and knowing that it's also building at the time of publish is irrelevant to a user. 

![screen shot 2015-04-30 at 11 06 27 am](https://cloud.githubusercontent.com/assets/222285/7415776/0d95d4de-ef29-11e4-982d-95de64485a2d.png)

**Comment by ryanmark** [comment]
or just publish?

**Comment by laurenrabaino** [comment]
That's what I meant. Yes. Just Publish
