### ISSUE TITLE
What does "updgrade" do? I'm scared to click it.

### ISSUE THREAD

**Issue by laurenrabaino** [voxmedia/autotune#119]
![screen shot 2015-04-30 at 11 14 02 am](https://cloud.githubusercontent.com/assets/222285/7415947/0c76618a-ef2a-11e4-9ec9-c9e68bd701b7.png)

Do we need it?

**Comment by ryanmark** [comment]
When a project is created, it takes a snapshot of the blueprint. So if the blueprint is updated, it doesn't affect any existing projects. If you want a project to use the updated blueprint, click `upgrade`.

The button needs to go somewhere, maybe theres a better place for it.

**Comment by laurenrabaino** [comment]
Is this a thing that we'd expect editors/reporters to use? Or should it be a thing that engineers or PM runs on a case-by-case?

**Comment by ryanmark** [comment]
Probably not. We should hide it from editorial.
