### ISSUE TITLE
When a thumbnail is not defined for a blueprint, default to a generic fallback

### ISSUE THREAD

**Issue by laurenrabaino** [voxmedia/autotune#128]
![screen shot 2015-05-04 at 2 44 07 pm](https://cloud.githubusercontent.com/assets/222285/7459966/b0dbbfc2-f26d-11e4-90ee-8b4c5f828a4d.png)

**Comment by caseymm** [comment]
I think this has already been fixed since the Headline Generator is using a default image. I had specified in my config to look for a thumbnail, but hadn't included one, so those were broken becuase of me. They are now fixed.
