### ISSUE TITLE
All blueprints need  needs to be either a canonical meta that points back to the story, or it needs a noindex meta tag

### ISSUE THREAD

**Issue by laurenrabaino** [voxmedia/autotune#129]
To avoid the embed versions being indexed by Google
![screen shot 2015-05-05 at 8 46 18 am](https://cloud.githubusercontent.com/assets/222285/7472742/a12b33be-f303-11e4-96e5-0a09ea4ed2bc.png)

**Comment by ryanmark** [comment]
This is something that each blueprint has to implement properly

**Comment by ryanmark** [comment]
Should we fix this one?
