### ISSUE TITLE
Wireframe revisions, round 1

### ISSUE THREAD

**Issue by laurenrabaino** [voxmedia/autotune#134]
**List view:**
- [x] Add timestamp - sorted by last modified, timestamp displayed only on publish. 
- [x] Add published status 
- [x] Add type of blueprint column
- [x] Get rid of upgrade button
- [x] Get rid of rebuild and destroy from this screen. 
- [x] If we only have one button, change up columns on list view page to make better use of space
- [x] Remove "projects" title from projects page since this is the main dashboard

**Edit page:**
- [x] Add delete to the edit page. 
- [x] Keep people on the page when they hit save; don’t go to dashboard or preview. 
- [x] Add option for viewing preview at the bottom of the page after you’ve hit save
- [x] Change building indicator to animated
- [x] Change the building indicator on the dashboard too
- [x] Move error messages lower
- [x] Add publish button to bottom next to saved / preview. Keep workflow process at bottom of the form
- [x] One column for forms. 
- [x] Narrower column well for large screens. 
- [x] Title, slug vertical are on every single project; always group them together since they are bare minimum. Always group them as “Project info” 
- [x] Add placeholder text; easy to add helper text —> move it up.
- [x] Add description text to the top. All other instructions should be included alongside the step you’re working with. Can put HTML in the helper text, josh maybe mock up the helper text with base images. 

**Main nav**
- [x] Help field in the nav — not a tutorial but maybe a FAQ 
- [x] Can get rid of the breadcrumb. Might suggest it’s more complicated than it is

**Things to explore:**
- [ ] Put new project button in the header? Explore this
- [x] To try: maybe there’s a tabbed way of grouping everything (preview / embed) on to the same page?

**Comment by ryanmark** [comment]
How did you get this to be checkboxes? thats neat!

**Comment by laurenrabaino** [comment]
:sparkles: ` - [ ]`

**Comment by cloudbring** [comment]
:dizzy:
