### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by ryanmark** [voxmedia/autotune#138]
The list of projects is gonna get long, and performance is gonna suffer, so we're gonna need to implement pagination in the API and in the UI.

- [x] Pick a gem
- [ ] Decide how to format the list JSON to include pagination info (page, num_pages)
- [ ] Update unit tests
- [ ] Rework Backbone app to handle pagination
- [ ] Pagination design (use bootstrap for now)
- [ ] QA

**Comment by ryanmark** [comment]
Need to pick a pagination gem: https://github.com/amatsuda/kaminari or https://rubygems.org/gems/will_paginate

**Comment by edenthecat** [comment]
We're going to use will_paginate due to the fact that it's used in chorus, for consistency.
