### ISSUE TITLE
Timezones support

### ISSUE THREAD

**Issue by ryanmark** [voxmedia/autotune#146]
bah, humbug!

**Comment by ryanmark** [comment]
So we should try to detect the browser timezone and shift displayed datetimes to match. Will have to add moment.timezone to the npm package and require it into the js app

**Comment by kavyasukumar** [comment]
Already set up to display local time
From machine on PST:
![screen shot 2015-05-28 at 2 26 12 pm](https://cloud.githubusercontent.com/assets/5184932/7867687/8fff5710-0545-11e5-8cf9-aca7fa416682.png)

From machine on EST:
![screen shot 2015-05-28 at 2 27 57 pm](https://cloud.githubusercontent.com/assets/5184932/7867791/0f2774e6-0546-11e5-9d5b-236155c90d7f.png)
