### ISSUE TITLE
Cannot preview projects on project page

### ISSUE THREAD

**Issue by kelseyscherer** [voxmedia/autotune#150]
On production

After successfully building a project, this is what you see: 
![image](https://cloud.githubusercontent.com/assets/5759653/7657872/8ffe4844-fb03-11e4-8224-da636715f024.png)
Expected: you should be previewing the project here.
Note: preview is working as expected in a new tab when you click `preview`

**Comment by ryanmark** [comment]
Should be fixed now. Had to adjust deployment settings.
