### ISSUE TITLE
Deleted projects are still listed in the projects dashboard

### ISSUE THREAD

**Issue by nanseay** [voxmedia/autotune#164]
When a user deletes a project, it should be removed from the projects dashboard

1) Login to autotune
2) create a project 
3) delete project https://autotune.voxmedia.com/projects/name-my-pet-4

Expected: project name should be removed from list of projects
Actual: deleted projects still in list, but if you click on the deleted project's headline 
![autotune deleted project 404](https://cloud.githubusercontent.com/assets/11615553/7683659/882fac82-fd4e-11e4-8f02-52931ed663d9.gif)

**Comment by ryanmark** [comment]
need to retest

**Comment by nanseay** [comment]
Verified as fixed, deleted projects are no longer listed in the projects dashboard
