### ISSUE TITLE
Should we display the username of the person who made the project?

### ISSUE THREAD

**Issue by laurenrabaino** [voxmedia/autotune#165]
And can we?

**Comment by nanseay** [comment]
+1 on the question and to be able to filter projects by owner on the dashboard

**Comment by ryanmark** [comment]
Add fields to the project API for now.

Permanent solution related to #210 and #103. We should add a user API for #103 and use that to retrieve user data to display in the list.

**Comment by ryanmark** [comment]
also, no filtering by user for now.
