### ISSUE TITLE
Image slider blueprint missing

### ISSUE THREAD

**Issue by jhdouglas** [voxmedia/autotune#166]
Upon creating a new project, users can select from three blueprints including the image slider. Both the Sortable table and Headline randomizer display correctly but the Image slider is currently missing.

1) Navigate to autotune
2) Create new project (https://autotune.voxmedia.com/projects/new)
3) Observe image slider missing from list of blueprints

![screenshot 2015-05-18 11 11 31](https://cloud.githubusercontent.com/assets/5640831/7683784/4c18b72e-fd4f-11e4-80a8-9bbbe6d46e69.png)

**Comment by laurenrabaino** [comment]
I added it back, should be there now @jhdouglas
