### ISSUE TITLE
Add ability to close notifications

### ISSUE THREAD

**Issue by jhdouglas** [voxmedia/autotune#168]
Notifications display when certain actions or errors occur. These messages display at the top of the screen. Similar to how Anthem offers the ability to close these alerts, it might be beneficial to add this option to Autotune. Because these alerts persist until the page is reloaded, users may appreciate the ability to dismiss them without having to reload.

1) Navigate to autotune (https://autotune.voxmedia.com/)
2) From list of created projects delete one
3) Confirm deletion
4) Observe notification displays at the top of the screen
5) Note no way to dismiss without reloading

Anthem:
![screenshot 2015-05-18 11 19 56](https://cloud.githubusercontent.com/assets/5640831/7684311/0981a5b6-fd53-11e4-8b5a-64789f04b698.png)

Autotune:
![screenshot 2015-05-18 11 24 39](https://cloud.githubusercontent.com/assets/5640831/7684314/12cb103a-fd53-11e4-892e-0f30c12262b7.png)

**Comment by laurenrabaino** [comment]
This is great big +1
