### ISSUE TITLE
IE11: double arrows displayed in projects dashboard filter drop down

### ISSUE THREAD

**Issue by nanseay** [voxmedia/autotune#173]
1) Navigate to the Projects dashboard on Autotune in IE11 
https://autotune.voxmedia.com/projects

Expected: single arrow per filter drop down
Actual: there are 2 arrows for each filter drop down

![ie11 autotune drop down](https://cloud.githubusercontent.com/assets/11615553/7686275/9dfb75dc-fd62-11e4-9db4-3688589d985a.PNG)

**Comment by zohf** [comment]
This should be fixed, can we retest @nanseay?
