### ISSUE TITLE
Add success message when action is complete (building, publishing, etc.)

### ISSUE THREAD

**Issue by jhdouglas** [voxmedia/autotune#174]
A notification displays each time an action is performed, e.g. building a project, publishing a project, etc. However, these statuses do not update when the task is complete. The user is never given an indication as to when a process is finished.

1) Navigate to Autotune (https://autotune.voxmedia.com/)
2) Create new project
3) Save project to build it
4) On dashboard observe project is building
5) Note no indication project is finished building
6) Refresh page
7) Observe status changes

![screenshot 2015-05-18 13 47 29](https://cloud.githubusercontent.com/assets/5640831/7686882/2290fe76-fd67-11e4-9664-de9d1df24c69.png)

![screenshot 2015-05-18 14 01 23](https://cloud.githubusercontent.com/assets/5640831/7686887/278b06f6-fd67-11e4-8397-6c54a9edf2f1.png)

**Comment by laurenrabaino** [comment]
@kavyasukumar didn't you work for a bit on getting the status to live-update without refreshing the page? Is this a bug on production?

**Comment by ryanmark** [comment]
Need to retest

**Comment by nanseay** [comment]
I still have to manually refresh the page to get updates
