### ISSUE TITLE
Remove line breaks in embed code

### ISSUE THREAD

**Issue by laurenrabaino** [voxmedia/autotune#176]
Remove the line breaks in this embed code so that when it gets pasted into TinyMCE (or sent there via Anthem), the scripts don't get wrapped in paragraph tags. 

```
<div data-analytics-class="embed" id="fun-weather__graphic"></div>
<script src="https://apps.voxmedia.com/at-preview/fun-weather/javascripts/pym.js" type="text/javascript"></script>
<script type="text/javascript">
new pym.Parent('fun-weather__graphic', 'https://apps.voxmedia.com/at-preview/fun-weather/', {xdomain: '.*\.voxmedia\.com'});
</script>
```

**Comment by ryanmark** [comment]
needs to be fixed by the blueprints

**Comment by laurenrabaino** [comment]
I wish there was a way to assign one issue to many repos 😾

**Comment by caseymm** [comment]
Changed for all blueprints other than the flowchart and quiz. Having issues with pym when I'm loading those - so that still needs to be figured out.

**Comment by caseymm** [comment]
Needs to be all one line. Period.

**Comment by caseymm** [comment]
Fixed for three going live at launch. Still need to edit those remaining.

**Comment by ryanmark** [comment]
Hey we could just strip out all line breaks when displaying the embed code in autotune.

**Comment by laurenrabaino** [comment]
+1
