### ISSUE TITLE
Why are we adding `Autotune` to the blueprint name?

### ISSUE THREAD

**Issue by laurenrabaino** [voxmedia/autotune#179]
Whack
![screen shot 2015-05-19 at 7 19 33 pm](https://cloud.githubusercontent.com/assets/222285/7716063/1260d7e2-fe5c-11e4-9026-9140a29163fd.png)

**Comment by ryanmark** [comment]
We're displaying the name from the blueprint itself, not the one you enter when you create a blueprint. Opened a ticket to fix.
