### ISSUE TITLE
Publishing breaks my heart

### ISSUE THREAD

**Issue by laurenrabaino** [voxmedia/autotune#181]
Every time I try to publish on staging, the "Publish" button turns into a "loading" button and I get this error: `Something bad happened... Please reload and try again`

**Comment by laurenrabaino** [comment]
**Steps to reproduce**
1. Navigate to this project: http://staging.autotune.voxmedia.com/projects/sort-me
2. Click `publish`
3. Observe error.

Expected result: The project publishes; embed code generated; embed code works in chorus; preview URL works.

Actual result: Page gets stuck on endless `loading` message and an error notification displays.

**Comment by ryanmark** [comment]
can't reproduce, could it maybe be happening on first time publish?
