### ISSUE TITLE
Automatic status updates are unreliable

### ISSUE THREAD

**Issue by ryanmark** [voxmedia/autotune#187]
So the automatic status updater disconnects and reconnects often. So often it's not connected when you really need it to be, and it's connected when you don't.

Some options:
- display some sort of notification when the updater is not connected so the user knows that she has to reload to see changes
- Keep the updater connected always. Figure out the ops stuff so this can happen.
- Only connect the updater when the user takes action that will cause status changes, disconnect after those statuses resolve.

**Comment by kavyasukumar** [comment]
Leaving this open for verification.
