### ISSUE TITLE
Embed codes are broken for sortable table

### ISSUE THREAD

**Issue by nanseay** [voxmedia/autotune#189]
I think the latest push to production broke the embed codes.  The base url is repeated - see highlight in screenshot
![autotune embed code](https://cloud.githubusercontent.com/assets/11615553/7732505/9200df5c-fef6-11e4-93c1-aa3e91f10915.png)

**Comment by alfeay** [comment]
[This issue was resolved](https://github.com/voxmedia/autotune-sortable-table/issues/20) this morning. Be sure to upgrade the blueprint before creating a new `autotune-sortable-table` project.
