### ISSUE TITLE
src urls in the embed codes should be http not https

### ISSUE THREAD

**Issue by nanseay** [voxmedia/autotune#192]
the source urls in the embed codes are https, but they should be http.
![autotune embed https](https://cloud.githubusercontent.com/assets/11615553/7735675/a86a0046-ff0c-11e4-8834-5b86b10cb302.png)

**Comment by alfeay** [comment]
Should be okay for js sources, it's the iframe that might cause issues in Firefox.

**Comment by alfeay** [comment]
According to @ryanmark, assets should be linked via the same protocol that is used to transmit the page. Since we're going `http` for the page, we should go `http` for the js.

**Comment by nanseay** [comment]
Created new defect with more details https://github.com/voxmedia/autotune/issues/194
