### ISSUE TITLE
Redis connection gets stuck in subscribe mode

### ISSUE THREAD

**Issue by ryanmark** [voxmedia/autotune#196]
Redis::CommandError
    ERR only (P)SUBSCRIBE / (P)UNSUBSCRIBE / QUIT allowed in this context

    Stacktrace (most recent call first):

      redis/client.rb:113:in `call'
        raise reply if reply.is_a?(CommandError)
      redis.rb:2022:in `block in publish'
        client.call([:publish, channel, message])
      redis.rb:37:in `block in synchronize'
        mon_synchronize { yield(@client) }
      monitor.rb:211:in `mon_synchronize'
        yield
      redis.rb:37:in `synchronize'
        mon_synchronize { yield(@client) }
      redis.rb:2021:in `publish'
        synchronize do |client|
      autotune/project.rb:95:in `pub_to_redis'
        Autotune.redis.publish 'projects', msg.to_json
      active_support/callbacks.rb:427:in `block in make_lambda'
        lambda { |target, _, &blk| target.send filter, &blk }
      active_support/callbacks.rb:225:in `call'
        user_callback.call target, value
      active_support/callbacks.rb:225:in `block in halting_and_conditional'
        user_callback.call target, value
      active_support/callbacks.rb:92:in `call'
        runner.call(e).value
      active_support/callbacks.rb:92:in `_run_callbacks'
        runner.call(e).value
      active_support/callbacks.rb:734:in `_run_save_callbacks'
        _run_callbacks(_#{name}_callbacks, &block)
      active_record/callbacks.rb:302:in `create_or_update'
        _run_save_callbacks { super }
      active_record/persistence.rb:120:in `save'
        create_or_update
      active_record/validations.rb:37:in `save'
        perform_validations(options) ? super : false
      active_record/attribute_methods/dirty.rb:21:in `save'
        if status = super
      active_record/transactions.rb:286:in `block (2 levels) in save'
        with_transaction_returning_status { super }
      active_record/transactions.rb:347:in `block in with_transaction_returning_status'
        status = yield
      active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
        yield
      active_record/transactions.rb:220:in `transaction'
        connection.transaction(options, &block)
      active_record/transactions.rb:344:in `with_transaction_returning_status'
        self.class.transaction do
      active_record/transactions.rb:286:in `block in save'
        with_transaction_returning_status { super }
      active_record/transactions.rb:301:in `rollback_active_record_state!'
        yield
      active_record/transactions.rb:285:in `save'
        rollback_active_record_state! do
      active_record/persistence.rb:250:in `block in update'
        save
      active_record/transactions.rb:347:in `block in with_transaction_returning_status'
        status = yield
      active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
        transaction_manager.within_new_transaction(options) { yield }
      active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
        yield
      active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
        transaction_manager.within_new_transaction(options) { yield }
      active_record/transactions.rb:220:in `transaction'
        connection.transaction(options, &block)
      active_record/transactions.rb:344:in `with_transaction_returning_status'
        self.class.transaction do
      active_record/persistence.rb:248:in `update'
        with_transaction_returning_status do
      autotune/project.rb:60:in `build_and_publish'
        update(:status => 'building')
      autotune/projects_controller.rb:86:in `build_and_publish'
        instance.build_and_publish
      action_controller/metal/implicit_render.rb:4:in `send_action'
        ret = super
      abstract_controller/base.rb:198:in `process_action'
        send_action(method_name, *args)
      action_controller/metal/rendering.rb:10:in `process_action'
        super
      abstract_controller/callbacks.rb:20:in `block in process_action'
        super
      active_support/callbacks.rb:117:in `call'
        env.value = !env.halted && (!block || block.call)
      active_support/callbacks.rb:117:in `call'
        env.value = !env.halted && (!block || block.call)
      active_support/callbacks.rb:151:in `block in halting_and_conditional'
        next_callback.call env
      active_support/callbacks.rb:151:in `call'
        next_callback.call env
      active_support/callbacks.rb:151:in `block in halting_and_conditional'
        next_callback.call env
      active_support/callbacks.rb:169:in `call'
        next_callback.call env
      active_support/callbacks.rb:169:in `block in halting'
        next_callback.call env
      active_support/callbacks.rb:169:in `call'
        next_callback.call env
      active_support/callbacks.rb:169:in `block in halting'
        next_callback.call env
      active_support/callbacks.rb:92:in `call'
        runner.call(e).value
      active_support/callbacks.rb:92:in `_run_callbacks'
        runner.call(e).value
      rack/session/abstract/id.rb:220:in `call'
        context(env)
      new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
        result = (target == self) ? traced_call(env) : target.call(env)
      action_dispatch/middleware/cookies.rb:560:in `call'
        status, headers, body = @app.call(env)
      new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
        result = (target == self) ? traced_call(env) : target.call(env)
      active_record/query_cache.rb:36:in `call'
        response = @app.call(env)
      new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
        result = (target == self) ? traced_call(env) : target.call(env)
      active_record/connection_adapters/abstract/connection_pool.rb:647:in `call'
        response = @app.call(env)
      new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
        result = (target == self) ? traced_call(env) : target.call(env)
      action_dispatch/middleware/callbacks.rb:29:in `block in call'
        @app.call(env)
      active_support/callbacks.rb:88:in `call'
        block.call if block
      active_support/callbacks.rb:88:in `_run_callbacks'
        block.call if block
      active_support/callbacks.rb:734:in `_run_call_callbacks'
        _run_callbacks(_#{name}_callbacks, &block)
      active_support/callbacks.rb:81:in `run_callbacks'
        send "_run_#{kind}_callbacks", &block
      action_dispatch/middleware/callbacks.rb:27:in `call'
        result = run_callbacks :call do
      new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
        result = (target == self) ? traced_call(env) : target.call(env)
      action_dispatch/middleware/remote_ip.rb:78:in `call'
        @app.call(env)
      new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
        result = (target == self) ? traced_call(env) : target.call(env)
      action_dispatch/middleware/debug_exceptions.rb:17:in `call'
        _, headers, body = response = @app.call(env)
      new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
        result = (target == self) ? traced_call(env) : target.call(env)
      action_dispatch/middleware/show_exceptions.rb:30:in `call'
        @app.call(env)
      new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
        result = (target == self) ? traced_call(env) : target.call(env)
      rails/rack/logger.rb:38:in `call_app'
        resp = @app.call(env)
      rails/rack/logger.rb:20:in `block in call'
        logger.tagged(compute_tags(request)) { call_app(request, env) }
      active_support/tagged_logging.rb:68:in `block in tagged'
        formatter.tagged(*tags) { yield self }
      active_support/tagged_logging.rb:26:in `tagged'
        yield self
      active_support/tagged_logging.rb:68:in `tagged'
        formatter.tagged(*tags) { yield self }
      rails/rack/logger.rb:20:in `call'
        logger.tagged(compute_tags(request)) { call_app(request, env) }
      new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
        result = (target == self) ? traced_call(env) : target.call(env)
      action_dispatch/middleware/request_id.rb:21:in `call'
        @app.call(env).tap { |_status, headers, _body| headers["X-Request-Id"] = env["action_dispatch.request_id"] }
      new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
        result = (target == self) ? traced_call(env) : target.call(env)
      rack/methodoverride.rb:22:in `call'
        @app.call(env)
      new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
        result = (target == self) ? traced_call(env) : target.call(env)
      rack/runtime.rb:18:in `call'
        status, headers, body = @app.call(env)
      new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
        result = (target == self) ? traced_call(env) : target.call(env)
      rack/sendfile.rb:113:in `call'
        status, headers, body = @app.call(env)
      new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
        result = (target == self) ? traced_call(env) : target.call(env)
      action_dispatch/middleware/ssl.rb:24:in `call'
        status, headers, body = @app.call(env)
      new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
        result = (target == self) ? traced_call(env) : target.call(env)
      raven/integrations/rack.rb:54:in `call'
        response = @app.call(env)
      new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
        result = (target == self) ? traced_call(env) : target.call(env)
      rails/engine.rb:518:in `call'
        app.call(env)
      rails/application.rb:164:in `call'
        super(env)
      new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
        result = (target == self) ? traced_call(env) : target.call(env)
      unicorn/http_server.rb:576:in `process_client'
        status, headers, body = @app.call(env = @request.read(client))
      unicorn/http_server.rb:670:in `worker_loop'
        process_client(client)
      unicorn/http_server.rb:525:in `spawn_missing_workers'
        worker_loop(worker)
      unicorn/http_server.rb:140:in `start'
        spawn_missing_workers
      /home/autotune/shared/bundle/ruby/2.1.0/gems/unicorn-4.8.3/bin/unicorn:126:in `<top (required)>'
        Unicorn::HttpServer.new(app, options).start.join
      /home/autotune/shared/bundle/ruby/2.1.0/bin/unicorn:23:in `load'
        load Gem.bin_path('unicorn', 'unicorn', version)
      /home/autotune/shared/bundle/ruby/2.1.0/bin/unicorn:23:in `<main>'
        load Gem.bin_path('unicorn', 'unicorn', version)

**Comment by kavyasukumar** [comment]
Could not consistently repro the bug. Attempting fix based on http://stackoverflow.com/questions/22668244/should-i-use-separate-connections-for-pub-and-sub-with-redis
