### ISSUE TITLE
Image slider embeds don't always display properly in Chorus entries

### ISSUE THREAD

**Issue by nanseay** [voxmedia/autotune#203]
May be related to #194?

1) Navigate to an entry with an image slider embed
Example - http://vox.sb5.sbndev.net/2015/5/20/8003334/feature-image-slider-embed
2) Click on full screen in your browser (gif is from Chrome on my mac, but I've seen it inconsistently on FF, Chrome, and Safari)

Expected: image slider loads correctly
Actual: image loads correctly after I click on full screen in my browser (it also sometimes works if I just refresh the page)
![image slider embed 2](https://cloud.githubusercontent.com/assets/11615553/7754631/221c439a-ffbc-11e4-9e9e-774985300a52.gif)

**Comment by caseymm** [comment]
![screen shot 2015-05-21 at 4 18 23 pm](https://cloud.githubusercontent.com/assets/3526984/7758107/098aab14-ffd5-11e4-84de-5dad1b161a4d.png)
Also, this happens to me when I refresh full screen.

**Comment by nanseay** [comment]
This is still reproducible for me

**Comment by caseymm** [comment]
Related to: https://github.com/voxmedia/autotune-image-slider/issues/8
