### ISSUE TITLE
IE: sortable table embeds aren't displaying properly

### ISSUE THREAD

**Issue by nanseay** [voxmedia/autotune#204]
Unable to see data from embedded sortable table in IE, nothing below the headers are displayed.  Note: Reproducible on all our versions of Internet Explorer and all breakpoints

1) Launch an article with a sortable table embedded
Example - http://polygon.sb5.sbndev.net/2015/5/20/8003331/article-sortable-table-embed 

Expected: sortable table loads successfully
Actual: table ends after the table headers, the rows of data are missing

![ie11 sortable table](https://cloud.githubusercontent.com/assets/11615553/7755625/827684b0-ffc3-11e4-8eff-e15c855840a9.PNG)

**Comment by ryanmark** [comment]
works for me after I updated to the new embed code

**Comment by caseymm** [comment]
Kavya gets a :star2: for figuring out that we needed `height`:`auto` instead of `height`:`initial`
