### ISSUE TITLE
Clicking the preview icon from the dashboard opens autotune.voxmedia.com

### ISSUE THREAD

**Issue by laurenrabaino** [voxmedia/autotune#215]
![screen recording 2015-06-01 at 12 55 pm](https://cloud.githubusercontent.com/assets/222285/7918203/a47d704e-085d-11e5-8f93-b66ceb0335c9.gif)

**Comment by laurenrabaino** [comment]
closing, a dupe of: https://github.com/voxmedia/vox-autotune/issues/26

**Comment by ryanmark** [comment]
fixed by https://github.com/voxmedia/autotune/commit/d6580d40700392f3dccbfe943ca52a8c79a96b6e
