### ISSUE TITLE
Make the `building` UI more obvious

### ISSUE THREAD

**Issue by laurenrabaino** [voxmedia/autotune#225]
During almost every user test we've conducted with new users, people are confused about what happens after they hit `save`. They tend to think they broke the project or did something wrong, then go back to look for an error message. After we've pointed out the `building....` message (which they overlook), it becomes more clear. 

To do: 
- [x] Make build UI more obvious on the page (using the same pattern, possibly, as the  `Project Saved` UI that displays on the bottom right of the screen) 
- [x] Add some concept of active building, either through a spinner or loading gif. This has been requested by multiple users who see the static `Building...` word as a frozen action (can't tell something is actively happening).

**Comment by ryanmark** [comment]
Is there more we want to do for this?
