### ISSUE TITLE
Pagination with filters is weird

### ISSUE THREAD

**Issue by ryanmark** [voxmedia/autotune#230]
So pagination happens on the server while filtering happens on the client. As a result each page is shorter than 30 when filters are applied, and it's possible that some pages show up empty.

- [x] remove the code that filters the list in the javascript template
- [x] Pass the filters to the `.fetch` call in the route, and figure how to pass filters through when using backbone paginator

**Comment by caseymm** [comment]
Ended up having to rewrite a bit of this along with getting the search functionality to work correctly in #221. Didn't mean to step on your toes, but the issues were basically one in the same when it came down to it.
