### ISSUE TITLE
Click next or prev page buttons should return you to top of page

### ISSUE THREAD

**Issue by ryanmark** [voxmedia/autotune#232]
Clicking on next or prev does not reset your scroll position.

**Comment by ryanmark** [comment]
Cause this is a js app, the browser doesn't know how to manage the scroll positions. There is code in `BaseView#render` to manage scroll position if a view is re-rendered. May need add something to `Router#everyRoute` to reset the scroll position when navigating between pages.

**Comment by caseymm** [comment]
So it looks like every time a page is re-rendered (this chunk: https://github.com/voxmedia/autotune/blob/dwi/appjs/views/BaseView.js#L38-L46), `view.firstRender` is always being reset to `true`, so it never gets to the `else` statement.

Forcing `scrollTop` on `getPageUrl` (https://github.com/voxmedia/autotune/blob/bfd65afd1f5a4beeba2f087354e9b6b173dbf519/appjs/helpers.js#L47) technically fixes this issue; however, it wouldn't be necessary if we were able to solve the issue noted above.
