### ISSUE TITLE
Blueprints can not be deleted

### ISSUE THREAD

**Issue by edenthecat** [voxmedia/autotune#235]
When deleting a blueprint, an error appears that states that blueprint can not be deleted unless it is not in use.

I've deleted all of the 'Sortable Table' type projects, yet this error continues to appear when trying to delete the blueprint: 
!['Error'](http://i.imgur.com/644DhsT.png)

**Comment by caseymm** [comment]
@edenthecat Was this local or staging? Currently unable to reproduce, so I'm trying to get the best picture I can.

**Comment by caseymm** [comment]
Still unable to duplicate.
