### ISSUE TITLE
Can't clone chorus_api_client-ruby.git when installing a test blueprint

### ISSUE THREAD

**Issue by henryleparisien** [voxmedia/autotune#237]
Hello everybody, first things first I want to thank you for this amazing work !

I don't know if this issue belongs here or on the blueprint repo 
I ran into a problem while trying to install "autotune-image-slider"  blueprint : after a few seconds it's flagged as "broken"

Here is the lines I get when checking http://localhost:3000/resque/failed

Worker
fluffy:3321 on DEFAULT at about 15 hours ago Retry or Remove
Class
 ActiveJob::QueueAdapters::ResqueAdapter::JobWrapper
Arguments

job_class: Autotune::SyncBlueprintJob
job_id: b97ad1e1-46ab-46ea-8406-b954ccd1e094
queue_name: default
arguments:
- _aj_globalid: gid://autotune-app/Autotune::Blueprint/4
Exception
WorkDir::CommandError
Error
bundle install --path .bundle --deployment Fetching gem metadata from http://rubygems.org/......... Fetching version metadata from http://rubygems.org/... Fetching dependency metadata from http://rubygems.org/.. Fetching git@github.com:voxmedia/chorus_api_client-ruby.git Warning: Identity file not accessible: No such file or directory. ERROR: Repository not found. fatal: Could not read from remote repository. Please make sure you have the correct access rights and the repository exists. Retrying git clone 'git@github.com:voxmedia/chorus_api_client-ruby.git' "/my-path/working/blueprints/coucou3/.bundle/ruby/2.1.0/cache/bundler/git/chorus_api_client-ruby-d056171939aa9d00ac137abda5f1e6edb5588f89" --bare --no-hardlinks --quiet due to error (2/4): Bundler::Source::Git::GitCommandError Git error: command `git clone 'git@github.com:voxmedia/chorus_api_client-ruby.git' "/my-path/working/blueprints/coucou3/.bundle/ruby/2.1.0/cache/bundler/git/chorus_api_client-ruby-d056171939aa9d00ac137abda5f1e6edb5588f89" --bare --no-hardlinks --quiet` in directory /my-path/working/blueprints/coucou3 has failed. Warning: Identity file not accessible: No such file or directory. ERROR: Repository not found. fatal: Could not read from remote repository. Please make sure you have the correct access rights and the repository exists. Retrying git clone 'git@github.com:voxmedia/chorus_api_client-ruby.git' "/my-path/working/blueprints/coucou3/.bundle/ruby/2.1.0/cache/bundler/git/chorus_api_client-ruby-d056171939aa9d00ac137abda5f1e6edb5588f89" --bare --no-hardlinks --quiet due to error (3/4): Bundler::Source::Git::GitCommandError Git error: command `git clone 'git@github.com:voxmedia/chorus_api_client-ruby.git' "/my-path/working/blueprints/coucou3/.bundle/ruby/2.1.0/cache/bundler/git/chorus_api_client-ruby-d056171939aa9d00ac137abda5f1e6edb5588f89" --bare --no-hardlinks --quiet` in directory /my-path/working/blueprints/coucou3 has failed. Warning: Identity file not accessible: No such file or directory. ERROR: Repository not found. fatal: Could not read from remote repository. Please make sure you have the correct access rights and the repository exists. Retrying git clone 'git@github.com:voxmedia/chorus_api_client-ruby.git' "/my-path/working/blueprints/coucou3/.bundle/ruby/2.1.0/cache/bundler/git/chorus_api_client-ruby-d056171939aa9d00ac137abda5f1e6edb5588f89" --bare --no-hardlinks --quiet due to error (4/4): Bundler::Source::Git::GitCommandError Git error: command `git clone 'git@github.com:voxmedia/chorus_api_client-ruby.git' "/my-path/working/blueprints/coucou3/.bundle/ruby/2.1.0/cache/bundler/git/chorus_api_client-ruby-d056171939aa9d00ac137abda5f1e6edb5588f89" --bare --no-hardlinks --quiet` in directory /my-path/working/blueprints/coucou3 has failed. Warning: Identity file not accessible: No such file or directory. ERROR: Repository not found. fatal: Could not read from remote repository. Please make sure you have the correct access rights and the repository exists. Git error: command `git clone 'git@github.com:voxmedia/chorus_api_client-ruby.git' "/my-path/working/blueprints/coucou3/.bundle/ruby/2.1.0/cache/bundler/git/chorus_api_client-ruby-d056171939aa9d00ac137abda5f1e6edb5588f89" --bare --no-hardlinks --quiet` in directory /my-path/working/blueprints/coucou3 has failed.

Looks like it's trying to clone a non-existing repo

Also, is it mandatory to have a chorus account to use this great product?

Thanks in advance

**Comment by ryanmark** [comment]
Huh, thanks for raising this!

That gem should not be required. I'll take a look.

**Comment by ryanmark** [comment]
Hey henryleparisien, you should try upgrading the blueprint to try it again. I pushed a change to https://github.com/voxmedia/autotune-image-slider to remove unnecessary stuff.
