### ISSUE TITLE
Figure out build process

### ISSUE THREAD

**Issue by ryanmark** [voxmedia/autotune#24]

**Comment by ryanmark** [comment]
Big question:
should each 'build' have it's own local copy of code and environment?
Should all the 'builds' share a single copy of the code and environment?

**Comment by laurenrabaino** [comment]
Need to understand pros/cons of each scenario.

**Comment by ryanmark** [comment]
# Isolated builds vs shared builds

## Shared builds
*pros*
- New builds complete quickly
- Builds always use most recent blueprint code
- Fewer server resources needed

*cons*
- Can only perform one build at a time per blueprint
- Potential for builds getting mixed up (mixing up html & css between different builds)
- Updates to blueprints affect all builds and will require testing
- Greater technical complexity in the autotune app, difficult to scale

## Isolated builds
*pros*
- Builds are targeted to a specific blueprint version, so they can always be rebuilt
- Builds cannot interfere with each other
- Blueprints can be updated without affecting old builds: less testing is needed for updates
- Many builds can be run at the same time using the same blueprint
- Implementation is simpler and more scalable

*cons*
- New builds need setup time before they're ready to be previewed or published
- More server resources are needed
- Updates to blueprints are not applied automatically to existing builds

**Comment by ryanmark** [comment]
Actually, nvm. We'll do isolated builds. We will be able to cache stuff locally to eliminate the setup time and most of the extra server resources.
