### ISSUE TITLE
Missing elements and fonts on screenshots

### ISSUE THREAD

**Issue by caseymm** [voxmedia/autotune#240]
<img width="822" alt="screen shot 2015-08-07 at 5 09 39 pm" src="https://cloud.githubusercontent.com/assets/3526984/9146022/3c6d94bc-3d27-11e5-8b7d-66bca72582be.png">

**Comment by ryanmark** [comment]
huh, thats bad. I think we may need to adjust the screenshot.js phantom script. And we also might change how we're loading fonts and such in the actual blueprints. I'm not sure.

**Comment by caseymm** [comment]
This is actually much better than I'd expected with fonts and such. Most of those seem to be coming through just fine, actually. 

I think the biggest problem is that phantom isn't waiting for the page to fully finish loading before taking the screenshot. This causes it to render screenshots with missing charts (https://autotune.voxmedia.com/projects/presidential-candidate-travel-2016) and cut off tables (https://autotune.voxmedia.com/projects/reddit-controversial-food-comments), for example.

<img width="740" alt="screen shot 2015-08-11 at 2 50 13 pm" src="https://cloud.githubusercontent.com/assets/3526984/9206866/51286774-4038-11e5-952b-806b1f967bf1.png">

**Comment by caseymm** [comment]
The changes I made do appear to work on staging (finishes loading the page before screenshotting), but I think that it may make the build process slower. 

Need to check if we could just have it take the screenshot on `publish` so that the initial build would be faster (and since we're not displaying the screenshots until the project is published) and see if there other possible ways to accomplish this.

e.g. Ryan's suggestion of loading the page once and then resizing it - though I think that may cause some issues with the smaller versions of some charts.

**Comment by ryanmark** [comment]
we could also enable disk cache for phantomjs, so it doesn't have to re-download assets in between runs

**Comment by caseymm** [comment]
Not sure exactly how much more we want to do with this/what the return on investment will really be. I can't speak for all verticals, but I know that Vox.com has included some screenshots that they've taken themselves in some tweets.

**Comment by ryanmark** [comment]
I'm inclined to remove this feature and instead implement something like pymviewer, maybe with the ability to take screenshot on the client side.

**Comment by ryanmark** [comment]
We are going to have to figure out how to take screenshots of this stuff if we want to support other platforms.

**Comment by caseymm** [comment]
Once we get live preview up, it might be fairly easy to get a client side screenshotting ability incorporated like you mention in the Sept 4 comment.
