### ISSUE TITLE
Project list should be filterable by 'Published/Draft' and blueprint name

### ISSUE THREAD

**Issue by ryanmark** [voxmedia/autotune#244]

**Comment by caseymm** [comment]
- published/draft can do into the `status` select box
- blueprint name will be a new box

**Comment by caseymm** [comment]
Remove `Pub/Draft` & `type` to make room

**Comment by caseymm** [comment]
That was supposed to be #250. ☝︎

**Comment by ryanmark** [comment]
The status dropdown shows the build statuses, should show `published`/`draft`
