### ISSUE TITLE
Theme name should not be automatically added to slug

### ISSUE THREAD

**Issue by ryanmark** [voxmedia/autotune#254]
Folks seem to want to remove the theme prefix from the slug when saving.

- [x] Don't automatically add the theme to the slug on the front-end UI
- [x] The slug field on the front end should display the slug sans theme
- [x] On project validation in rails, ensure the theme name is prefixed to the slug
- [x] On changed theme, ensure slug is updated to contain new theme name
- [x] Change the move work dir job to trigger on changed theme, in addition to slug

**Comment by alfeay** [comment]
Running successfully on staging. Still needs to be merged with master and deployed to production, but closing this.
