### ISSUE TITLE
Improve readability of error output for 422

### ISSUE THREAD

**Issue by aidanfeay** [voxmedia/autotune#266]
Example case: duplicate entry in CMS causing conflict
<img width="310" alt="screen shot 2015-09-16 at 11 47 26 am" src="https://cloud.githubusercontent.com/assets/6778548/9909978/bafe3894-5c68-11e5-96aa-8db6fc35a345.png">

**Comment by ryanmark** [comment]
I have a commit in chorus to return more specific error messages
