### ISSUE TITLE
Eternally "building" projects 

### ISSUE THREAD

**Issue by caseymm** [voxmedia/autotune#267]
Sometimes something goes awry during the build process and we end up with projects that never seem to resolve themselves: https://autotune.voxmedia.com/projects/vox-donald-trump-book-tax-plan.

**Comment by ryanmark** [comment]
I think this was caused by deploying. I think deploying seems to break any running builds.

**Comment by ryanmark** [comment]
So I tried rebuilding one project that was stuck on building... it kept getting stuck on building... until it didn't.

**Comment by caseymm** [comment]
Seems likely that deploying would be the cause. Actually, now that you mention it, I have accidentally mimicked that behavior locally by quitting and restarting while projects are building - which results in the eternal `building` status.

**Comment by ryanmark** [comment]
Updated deployment to reload resque instead of restart.
