### ISSUE TITLE
Fix social char count for open source blueprints

### ISSUE THREAD

**Issue by caseymm** [voxmedia/autotune#268]
<img width="329" alt="screen shot 2015-09-17 at 4 31 00 pm" src="https://cloud.githubusercontent.com/assets/3526984/9945144/9df222aa-5d59-11e5-8333-8e17a406bfd4.png">

**Comment by caseymm** [comment]
Assuming `Generic` as the default option, this will be fixed as soon as #274 is accepted.

**Comment by kavyasukumar** [comment]
Fixed as a part of https://github.com/voxmedia/autotune/pull/333
