### ISSUE TITLE
List editing buttons are gross

### ISSUE THREAD

**Issue by ryanmark** [voxmedia/autotune#273]
something happened to the list editing buttons:

<img width="393" alt="screen shot 2015-09-22 at 12 11 07 pm" src="https://cloud.githubusercontent.com/assets/114194/10025701/2864d99c-6123-11e5-8db3-f4e51f3fce5f.png">

**Comment by aidanfeay** [comment]
This should have been addressed by https://github.com/voxmedia/autotune/commit/76dd24a3d0fed3d9bf9c66d6ddecaec082e2d27b. Need verification of fix, but this is clearly the same bug.
