### ISSUE TITLE
Move social share character counts into theme model

### ISSUE THREAD

**Issue by ryanmark** [voxmedia/autotune#274]
We have vox-specific social share character counts hard-coded into `EditProject.js`. This should be configurable.

We should add a field to the theme rails model for this data (possibly via a `meta` json field).

**Comment by ryanmark** [comment]
Nice work. Now the `social_dict` you have hard-coded in the theme model should be a configuration thing: `Autotune.config.social_char_count`. Perhaps it would be more generally useful if instead of storing the number of characters in the twitter handle, we stored the twitter handle. In which case we wouldn't need to create a new configuration thing, we could extend the `themes` configuration thing. (This all fits nicely with more changes we'll have to make down the road for #265 ).

**Comment by kavyasukumar** [comment]
fixed as a part of https://github.com/voxmedia/autotune/pull/333
