### ISSUE TITLE
minor multipage layout issue in chrome

### ISSUE THREAD

**Issue by nanseay** [voxmedia/autotune#275]
Before saving - add a page icons lie within box
![before draft](https://cloud.githubusercontent.com/assets/11615553/10102879/fb2afd78-636e-11e5-9940-e185dbbe35f3.jpg)
After saving - the add a page icons lay outside of the box
![after draft publish](https://cloud.githubusercontent.com/assets/11615553/10102878/fb2aebda-636e-11e5-88fb-d6e568e5505e.jpg)

**Comment by nanseay** [comment]
@aidanfeay is this already deployed in staging?  If so, it doesn't look fixed 
![chrome layout](https://cloud.githubusercontent.com/assets/11615553/10107018/1ebc1c38-6386-11e5-904e-28a86c40d4c8.gif)

**Comment by aidanfeay** [comment]
@nanseay The build broke after commit, so I'm going to leave this open until that's resolved. I'll post back here when it's ready for verification.

**Comment by ryanmark** [comment]
duplicate of https://github.com/voxmedia/autotune/issues/273
