### ISSUE TITLE
Live preview mockup

### ISSUE THREAD

**Issue by ryanmark** [voxmedia/autotune#281]
- [x] Only for projects of type ‘graphic’
- [x] New tab available when editing or creating a project (preview)
- [x] Remove `screenshot` tab
- [x] When viewing the preview, should be able to change preview size ála pymviewer
- [x] Preview has two modes: live and regular
- [x] When viewing the preview, user should be able to tell if the preview is live or up-to-date or still building (live preview is a feature which each blueprint has to implement). Should add a banner message above the preview which says “This preview is up-to-date” or “This preview is out-of-date, new preview is building…”
- [x] Live preview is updated whenever the form is changed
- [x] Preview link and button switch to preview tab instead of opening a new window
- [x] When viewing live preview, should have a save button available (maybe?)

**Comment by caseymm** [comment]
### With preview tab
![live_preview_mocks-01](https://cloud.githubusercontent.com/assets/3526984/10648170/efd264d8-780a-11e5-8223-d99ef619c525.png)

### Live Preview
![live_preview_mocks-02](https://cloud.githubusercontent.com/assets/3526984/10648169/efd197d8-780a-11e5-93c0-5ce1ce5a1833.png)

### Regular preview
![live_preview_mocks-04](https://cloud.githubusercontent.com/assets/3526984/10648171/efd4022a-780a-11e5-8d8d-1524cc1b1a4b.png)

![live_preview_mocks-03](https://cloud.githubusercontent.com/assets/3526984/10648167/efd0d460-780a-11e5-9064-00f91a9e5546.png)

![live_preview_mocks-05](https://cloud.githubusercontent.com/assets/3526984/10648168/efd0a684-780a-11e5-8e66-d81820292d82.png)

**Comment by caseymm** [comment]
Is there a particular way that I should show some of the interactive elements in the mockup? For instance, how clicking the preview button would open the tab?

**Comment by caseymm** [comment]
Updated mocks are here: 

Timeline: https://drive.google.com/a/voxmedia.com/file/d/0B3nFdKjvjwBPeE1aZ0dtaVBUMkk/view?usp=sharing

Charts: https://drive.google.com/a/voxmedia.com/file/d/0B3nFdKjvjwBPck8yUnFCQjBDc28/view?usp=sharing

**Comment by caseymm** [comment]
Re two remaining issues:
- Not sure how we want to indicate to users that this is only for type `graphic`
- Do we want to have a `save` button on the live preview page?
