### ISSUE TITLE
Paper user test of live preview

### ISSUE THREAD

**Issue by ryanmark** [voxmedia/autotune#282]
The visible change in with the live preview will be the new location of the preview, and the workflow for previewing.

The major change will simply be that previews are automatically available.

Need to make sure that users feel that the new preview workflow feels natural and easy.
Need to make sure that users can recognize the difference between a _live_ preview that updates automatically and a regular preview that needs to be rebuilt.

Present new preview location to autotune users using mocks.

**Comment by caseymm** [comment]
Timeline: https://drive.google.com/a/voxmedia.com/file/d/0B3nFdKjvjwBPeE1aZ0dtaVBUMkk/view?usp=sharing

Charts: https://drive.google.com/a/voxmedia.com/file/d/0B3nFdKjvjwBPck8yUnFCQjBDc28/view?usp=sharing

**Comment by ryanmark** [comment]
These mockups are different from what you posted on the other issue - is this changed based on user feedback?

**Comment by caseymm** [comment]
No. I also updated the other issue. I realized this morning that it really needed more indication of whether or not it had a live preview ability, so I added a few things to it before I started testing this afternoon. I also realized that I should use a different blueprint for live/not live.

**Comment by caseymm** [comment]
Notes from user tests are here: https://docs.google.com/document/d/1RwWIWklqUkX9mS6GGJmJ-A2ojuOIZDHvHWEpAED0IeA/edit
