### ISSUE TITLE
allow form to stay collapsed once a user has collapsed it (retain form changes on reload)

### ISSUE THREAD

**Issue by aidanfeay** [voxmedia/autotune#283]
"We've gotten the request a few times as people are making gift guides, so want to document it

Since gift guides often have many products across lots of categories, it's hard to stay organized with so many form fields in Autotune. To make it more manageable, users often collapse sections so they don't have to scroll through a huge list. However, once you save and come back, the entire project is fully uncollapsed.

Request: if you collapse a section, it should remain collapse upon save and show collapsed when you return to the project.

This might be better suited to the autotune repo? I'm not sure."
 - via @kelseyscherer https://github.com/voxmedia/autotune-gift-guide/issues/122

**Comment by ryanmark** [comment]
We should check if this can be done in the `autotune-config.json`, maybe default to have products collapse by default?
