### ISSUE TITLE
Live Preview: Required fields on new projects highlighted by default

### ISSUE THREAD

**Issue by jhdouglas** [voxmedia/autotune#289]
Required fields within blueprints are denoted with a star. If a required field isn’t completed, then it becomes highlighted and displays a message to the user. Currently all new blueprints have these required fields highlighted by default on creation.

Note: This includes both live preview enabled blueprints and non-live preview blueprints.

1) Navigate to Autotune on staging
2) Create new project
3) Choose any blueprint with a required field (http://staging.autotune.voxmedia.com/blueprints/image-slider/new_project)
4) Observe required fields are highlighted by default

<img width="679" alt="screenshot 2015-12-11 10 40 04" src="https://cloud.githubusercontent.com/assets/5640831/11748160/eea006d0-9ff4-11e5-8349-ce1a63a5af5b.png">

<img width="798" alt="screenshot 2015-12-11 10 40 17" src="https://cloud.githubusercontent.com/assets/5640831/11748159/ec2189ba-9ff4-11e5-9564-b25007ac9d10.png">

**Comment by caseymm** [comment]
Ok, this should be fixed now.

**Comment by jhdouglas** [comment]
Verified fixed. All required fields are no longer highlighted when creating new project.
