### ISSUE TITLE
Live Preview: Timeline preview with dummy dataset unavailable after performing any action

### ISSUE THREAD

**Issue by jhdouglas** [voxmedia/autotune#290]
Live preview uses a dummy dataset if no values are entered. This is true for the timeline; however, if a user changes the theme from default SBNation, then preview becomes unavailable and no default dataset displays.

1) Navigate to Autotune on staging
2) Create new Timeline (live preview) project (http://staging.autotune.voxmedia.com/blueprints/timeline-live-preview/new_project)
3) Observe theme defaults to SBNation
4) Click preview tab to view dummy dataset
5) Change theme to any other vertical
6) Return to preview tab
7) Note dummy dataset unavailable

![livepreview_timeline](https://cloud.githubusercontent.com/assets/5640831/11749385/66af7fd8-9ffb-11e5-8c0f-fbaf424bdb7a.gif)

**Comment by jhdouglas** [comment]
This actually appears to occur if any action is taken. Filling in the title without adding data also causes the preview not to display. Updated title to reflect this.

**Comment by caseymm** [comment]
Ok, this should be fixed on staging now.

**Comment by jhdouglas** [comment]
Verified fixed. Timeline live preview now functions as expected and changing theme works correctly in preview.
