### ISSUE TITLE
Best UX for creating a new spreadsheet?

### ISSUE THREAD

**Issue by caseymm** [voxmedia/autotune#315]
Here's what I have now - want to get some opinions on the flow of this.

Currently, any blueprint that is detected as `live`, requires a `google_doc_url`, and includes a `spreadsheet_template` in the config will get a button like this added to the form in the Google spreadsheet URL section. It appears on both new and existing projects.

![screen shot 2016-01-26 at 9 48 40 am](https://cloud.githubusercontent.com/assets/3526984/12583838/a7be2b24-c412-11e5-8355-8fe9ec891f83.png)

If the input box is blank, Autotune will create the spreadsheet and automatically drop the link into the form. e.g.

![screen shot 2016-01-26 at 9 48 52 am](https://cloud.githubusercontent.com/assets/3526984/12583869/caf85d58-c412-11e5-8f98-6901362a06d7.png)

If the input box already contains text, it will prompt the user to confirm that he wants to replace the link and respond accordingly (will replace if confirmed or leave as is if cancelled). e.g.

![screen shot 2016-01-26 at 9 49 11 am](https://cloud.githubusercontent.com/assets/3526984/12583899/fefa0f8e-c412-11e5-925b-0cd34f934377.png)

You can try this out on staging [here](http://staging.autotune.voxmedia.com/blueprints/chartbuilder-mvp/new_project) or by creating a new chart.

------

I want to know what you all think of this flow overall, but I also have a couple of questions. Currently, creating a spreadsheet will always draw from the template link included in the config. I'm wondering what you all think about either

A) Generating a copy of the existing spreadsheet when the project already exists OR if it's a new `duplicate` project.

B) Creating a way for the user to select whether it generates a new spreadsheet from the template or a copy of the existing spreadsheet.

C) None of the above/other. 

I realize that allowing so many options could get messy rather quickly, but I wanted to get your opinions on the ideas I've listed as well as the workflow that is currently in place.

**Comment by ryanmark** [comment]
Would it be an improvement to change the button text to `new spreadsheet` or `get new spreadsheet` ?

**Comment by jasonsantamaria** [comment]
I was thinking the same thing about a clearer button label (or one that can change depending on if there is text present in the field.

As for your other question about generating a spreadsheet, how often does this action take place, and what is the most common following action (for instance, edit the structure heavily, or just change some values)?

**Comment by kelseyscherer** [comment]
+1 to clearer button label. I also think the language could indicate that you could either `make new spreadsheet` or `paste your own spreadsheet in` although I realize make new spreadsheet would be a button and paste your own link in would not be.

Also +1'ing Jason's comments. We should probably do what would be most useful for users. Are they typically using an empty template or just changing the values of an existing template?

**Comment by caseymm** [comment]
Re: Jason and Kelsey's 2nd paragraphs - Do you mean specifically regarding the questions I asked about changing the button behavior or for generating spreadsheets for new projects, too? I'm down to ask users about what would be most useful, but we also haven't ever included the ability to generate a spreadsheet like this before - only linked to examples that the user could copy - so I'm not sure what feedback I'd be looking for if the project is new (and not a duplicate).

**Comment by jasonsantamaria** [comment]
My comments were about your `ABC` options, I don't think I have enough info to make a call.

**Comment by ryanmark** [comment]
I wonder if this needs to be an open text box at all. If Autotune will automagically create a spreadsheet for you, when will you ever need to paste your own in there?

**Comment by caseymm** [comment]
I think there could be users that have already created a spreadsheet or found a dataset that they've put into a spreadsheet coming to autotune with the expectation of being able to just drop the link in. I think that dropping the input box could disrupt workflow for certain users. It is something else I could ask about, though. i.e.

**Comment by ryanmark** [comment]
My hunch is that never happens. The spreadsheets usually have very specific formats that must be followed. Just reusing a spreadsheet that you found or created for reporting almost certainly doesn't follow that format.

**Comment by caseymm** [comment]
Ok. I would still like to ask about it, though. That's also a pretty big change that I don't think we should drop before consulting at least some users about.

I realize that I'm not the typical user, but I change spreadsheet links in forms all of the time. Lets me change the project without overwriting what I have in the spreadshet so that I can just drop it back in if I decide I like that version better.
