### ISSUE TITLE
Live Preview: Small Multiples: Social share overlaps title at small breakpoint

### ISSUE THREAD

**Issue by jhdouglas** [voxmedia/autotune#319]
Users have several preview options, one of which is a small breakpoint. Currently, the social share icons overlap the title in the small multiples blueprint at small breakpoint preview.

1) Navigate to Autotune on staging
2) Create new small multiples project
3) Add required info and preview (http://staging.autotune.voxmedia.com/projects/eater-sm-live-preview)
4) Open small breakpoint
5) Observe social share overlaps title

![screenshot 2016-02-02 10 58 49](https://cloud.githubusercontent.com/assets/5640831/12755250/a58b06e4-c99c-11e5-9d8e-7584b95a749f.png)

**Comment by caseymm** [comment]
Closing this since it will eventually be part of QA for this blueprint when the time comes.
