### ISSUE TITLE
Rework field hiding

### ISSUE THREAD

**Issue by kavyasukumar** [voxmedia/autotune#339]
Autotune hides themes dropdown if there is only one available theme. This has unintended side effects. Alpaca doesn't seem to process dependencies for themes when `display` is none. This causes custom colors field to be not submitted

Theme hiding has been temporarily disabled : https://github.com/voxmedia/autotune/commit/c20c3a740539f17556578af3eab77ecf18521242

Potential workarounds: 
- Hide without display:none. i.e using visibility
- Patch alpaca

**Comment by katieodowd** [comment]
Good to close @caseymm?

**Comment by caseymm** [comment]
Assuming we are not going to spend the (extra) time to patch alpaca, yes, good to close since this fixed the issue.
