### ISSUE TITLE
Theme editor UI: Contrast problems

### ISSUE THREAD

**Issue by kelseyscherer** [voxmedia/autotune#344]
The light gray `#ccc` being used for secondary helper text in the themes UI is too light and difficult to read. It should be slightly lighter than the labels.

Currently:
![image](https://cloud.githubusercontent.com/assets/5759653/15611977/dc31d98a-23fa-11e6-8f93-ecd009826a62.png)

Mock for reference:
![image](https://cloud.githubusercontent.com/assets/5759653/15611990/eb0890fc-23fa-11e6-8cba-078456c892a2.png)

If you need particular hex codes for these two items let me know, I'm not sure what values of gray we are using for Autounes palette but I can suggest some.

**Comment by kavyasukumar** [comment]
This is the default bootstrap styling for helper text that is in use on all pages. I have changed it now to a slightly darker version. https://github.com/voxmedia/autotune/commit/6cbb4aa5f721f0e0aaab308d2d88730727090666

**Comment by kelseyscherer** [comment]
This is fine. I'll take another look at all the colors for things like help text and address contrast issues as a part of the project creation work.
