### ISSUE TITLE
Themes dropdown is too overwhelming for users with permissions to many sites

### ISSUE THREAD

**Issue by kelseyscherer** [voxmedia/autotune#345]
With the new theming work, we're putting SBN blogs onto the dropdown list of themes. Some users will have permissions to lots and lots of blogs. We should rethink the way users select a theme so that it's helpful for all users, whether they have permissions to 2 brands or 200. 

I suggest we wait to do this until we get further along with project creation, and tackle it as it's own project, with design explorations and considerations with a project doc that lists goals and different user behaviors.

![image](https://cloud.githubusercontent.com/assets/5759653/15612306/357c92cc-23fc-11e6-8198-75a6ea54ffdd.png)

**Comment by maclover7** [comment]
Could use something like [Chosen](http://harvesthq.github.io/chosen/) to make searching large lists easier.
