### ISSUE TITLE
Themes update: Racked headline is too heavy

### ISSUE THREAD

**Issue by kelseyscherer** [voxmedia/autotune#347]
Persistent across a couple of blueprints, using too heavy of a font for Racked. Should not be using `font-weight: 700` for Racked headlines.

Blueprints affected:

- Quiz
- Personality Quiz
- Sortable Table

Related issues:
https://github.com/voxmedia/autotune-quiz/issues/103
https://github.com/voxmedia/autotune-sortable-table/issues/76
https://github.com/voxmedia/autotune-personality-quiz/issues/40

**Comment by kavyasukumar** [comment]
Fixed by https://github.com/voxmedia/vox-autotune/commit/6fc4b577153423c032a57550dd7a4c32a7c0c4c1
