### ISSUE TITLE
Autotune rework: Editing forms for each blueprint

### ISSUE THREAD

**Issue by kelseyscherer** [voxmedia/autotune#352]
As I work through the best way to organize the editing forms / sidebars for each blueprint as a part of this redesign, I'm going to be dropping them into this github issue. 

For each blueprint, I'd like to group elements into sections in the sidebar. I'll list each one in it's own comment with a mock. Section titles are bold, and form labels are in the regular weight.

**Comment by kelseyscherer** [comment]
# Image slider
![autotune_blueprints-ks-1 1-02](https://cloud.githubusercontent.com/assets/5759653/16061791/2fb8a3b6-325d-11e6-851e-c05bae4e7671.jpg)

### Sections

**Preview**
- links to preview across breakpoints

**Project details**
- Title
- Theme 
- Social share

**First image**
- Url
- Credit 
- Credit source

**Second image**
- Url
- Credit 
- Credit source

**Slider bar details**
- options for dark or light slider bar

**Comment by kelseyscherer** [comment]
# Sortable table
![autotune_blueprints-ks-1 1-04](https://cloud.githubusercontent.com/assets/5759653/16061999/91711862-325e-11e6-8701-9f428bfd2d79.jpg)


### Sections

**Preview**
- links to preview across breakpoints

**Project details**
- Title
- Theme 
- Spreadsheet link
- Social share
- # of rows to show

**Sorting**
- Name of column to sort by
- Sort order

**Data citation**
- Citation
- Citation url
- + Add new citation button (would load another set of citation + url fields)

**Comment by caseymm** [comment]
I think this is good?

**Comment by kelseyscherer** [comment]
ya
