### ISSUE TITLE
Autotune rework: form order

### ISSUE THREAD

**Issue by kelseyscherer** [voxmedia/autotune#353]
![image](https://cloud.githubusercontent.com/assets/5759653/16062933/6fc5e606-3264-11e6-94c9-3212be3d2a0f.png)

Could we reorder the elements in the form? So instead of: 

1. Field label
2. Field
3. Help Text 
4. Warnings / Errors

It'd be

1. Field label
2. Help Text 
3. Field
4. Warnings / Errors

**Comment by caseymm** [comment]
I figured out how to move them all above... but that doesn't work so well for helpers on checkboxes and radio buttons... 

<img width="423" alt="screen shot 2016-06-15 at 11 32 36 am" src="https://cloud.githubusercontent.com/assets/3526984/16086284/03d9f9e4-32ed-11e6-9a5a-018f286ac0d8.png">

I feel like I should be able to figure out a way to render them above or below conditionally, but it will require more digging into alpaca.

**Comment by kelseyscherer** [comment]
Ooooohhh! I'm not totally convinced check boxes are the right solution for these interactions, or that check boxes should have helper text (i understand why it is that way currently, but I'm thinking there might be a better way). I will keep this in mind as I design out the side editing form for charts. Also ty 💪

**Comment by caseymm** [comment]
@kelseyscherer Ok to close this or do you want to leave open for v2 iteration on this?

**Comment by kelseyscherer** [comment]
Ok to close.
