### ISSUE TITLE
colors that are more accessible than our current colors (baby steps)

### ISSUE THREAD

**Issue by kelseyscherer** [voxmedia/autotune#355]
![autotune_colors-ks-1 3-01](https://cloud.githubusercontent.com/assets/5759653/16435133/cd0d37bc-3d61-11e6-8a6f-a69d5ea6f2c2.png)

Changes should be made to:

$light-actionable -> #656565
$negative-color ->  #FD432E

All button-color text should be #222222 (and same should be used for all messaging text color as well)

Trello card: https://trello.com/c/lhQYar9X/679-design-a11y-friendly-color-palette-for-autotune-6-28

**Comment by kelseyscherer** [comment]
Also would love for this to apply to the `status` labels on dashboards.

![image](https://cloud.githubusercontent.com/assets/5759653/16435411/c11b2c8c-3d63-11e6-8597-4a40a224edf2.png)

**Comment by caseymm** [comment]
Lmk how this looks now

**Comment by kelseyscherer** [comment]
Actual a11y friendly colors that are not horrible and ugly!

![image](https://cloud.githubusercontent.com/assets/5759653/16506776/c583508e-3ef2-11e6-93af-782821160adb.png)

In practice:
![image](https://cloud.githubusercontent.com/assets/5759653/16506781/d13145f8-3ef2-11e6-9e05-aa95bca8526f.png)

Primary action text color: `#0F286B`
Secondary action text color: `#222222` (same as before)
Positive text color when on `$positive-color` bg: `#223D02`
Negative text color when on `$negative-color` bg: `#550000`
Cautionary color when on `$cautionary-color` bg: `#282E35`

NOTE! Change `$negative-color` -> `#E83F3F`
