### ISSUE TITLE
Replace preview breakpoint icons to match chorus

### ISSUE THREAD

**Issue by kelseyscherer** [voxmedia/autotune#356]
Assets here: https://trello.com/c/uEtAxui7/689-design-get-anthem-preview-breakpoint-icons

**Comment by caseymm** [comment]
Icons should be showing up on staging now. I do have a question about what widths to hide them at, though. Need to tweak a few things regarding hiding the icons at certain breakpoints.

**Comment by caseymm** [comment]
@kelseyscherer Check this out and lmk?

**Comment by kelseyscherer** [comment]
Thanks! Few notes:

- Can we make the buttons 20px by 20px
- Can we make the buttons more square, less long rectangle?
- Can we make the `on` state the primary action color? (I know it's not an action but it should be a different color than dark gray)
- Can we go back to 3 buttons using all 3 icons: phone for small, tablet for medium, desktop for full. (I know this isn't exact, but it's close)

Trying to get close to this:
![image](https://cloud.githubusercontent.com/assets/5759653/16500423/79ba4e7a-3ed2-11e6-8c6f-910b5f8158d5.png)
Minus the white icons.

The trello card has the svgs with updated colors. (They are #222222 instead of #000000)
https://trello.com/c/uEtAxui7/689-design-get-anthem-preview-breakpoint-icons

**Comment by caseymm** [comment]
Put desktop icon back in if not small bp. Jumping from 3 to 1 would be ok.
