### ISSUE TITLE
Match blueprint + theme dashboards to project dashboards

### ISSUE THREAD

**Issue by kelseyscherer** [voxmedia/autotune#357]
Projects dashboard:
![image](https://cloud.githubusercontent.com/assets/5759653/16466443/2cc37a90-3e11-11e6-9146-db2af48f9534.png)
Project name + actionable icons are in $light-color, everything else in $light-actionable-color

Blueprints dashboard:
![image](https://cloud.githubusercontent.com/assets/5759653/16466469/49b24564-3e11-11e6-9cd3-d0756b3dba42.png)
Blueprint title + action icons should be $light-color

Themes dashboard:
![image](https://cloud.githubusercontent.com/assets/5759653/16466502/5f9262f6-3e11-11e6-83d5-7e85e3e0f5d9.png)
Theme name + action icons should be $light-color

**Comment by caseymm** [comment]
This should be good to go on staging.

**Comment by kelseyscherer** [comment]
Not seeing on staging. This is what I see:

![image](https://cloud.githubusercontent.com/assets/5759653/16491198/ed2adf00-3eaa-11e6-8696-40bc658931f8.png)

**Comment by caseymm** [comment]
Oh I think I did the opposite.

**Comment by caseymm** [comment]
This seems to be correct now, I think.

**Comment by kelseyscherer** [comment]
Blueprints page is :+1:.

On themes, `Groups` column should be $light-actionable-color (the lighter gray).

**Comment by caseymm** [comment]
I think this is fixed.
