### ISSUE TITLE
Autotune rework: use preview icons on publish tab under screenshots

### ISSUE THREAD

**Issue by kelseyscherer** [voxmedia/autotune#364]
Should not block redesign launch. Nice to have / fine to leave for future.

Would love to swap out these buttons for the preview icons (mobile, tablet, desktop) and show mobile first.
![image](https://cloud.githubusercontent.com/assets/5759653/16501842/72ac4730-3ed9-11e6-8a51-ed264806cdec.png)

**Comment by caseymm** [comment]
Should be on staging.

**Comment by caseymm** [comment]
Fix disappearing buttons... Good other than that.
