### ISSUE TITLE
Final icons for actions

### ISSUE THREAD

**Issue by kelseyscherer** [voxmedia/autotune#366]
Final icons for: 

- alert
- delete
- dropdown
- duplicate
- edit
- help
- info
- ok
- preview
- refresh

https://www.dropbox.com/sh/y0m60l1fcsfpp2n/AABRpz1bLBvV9IaM1_iva9gca?dl=0

Make sure all dashboards are using the same icons (currently they're still using different icons)

**Comment by caseymm** [comment]
Replaced them everywhere that I could remember we had them. On staging.

**Comment by caseymm** [comment]
Replace with square versions from Kelsey

**Comment by kelseyscherer** [comment]
@caseymm icons should be in square artboards now! https://www.dropbox.com/sh/y0m60l1fcsfpp2n/AABRpz1bLBvV9IaM1_iva9gca?dl=0
