### ISSUE TITLE
Add indication that editing panel can be resized

### ISSUE THREAD

**Issue by kelseyscherer** [voxmedia/autotune#373]
Currently, you can resize the editing panel in order to see more of the form. This is extremely helpful especially in blueprints like personality quiz and flowchart where there are multiple columns of inputs in a small sidebar.

However, there is no indication that users can resize this panel. We should design an indication that makes this interaction clear to users.

![img](https://i.gyazo.com/b20c431c4ae94819179ccb5a319d02f1.gif)

**Comment by caseymm** [comment]
I agree, but wasn't sure how to indicate. Maybe some sort of handle? Let me know what you'd like to add.

**Comment by caseymm** [comment]
This should be good to go on prod.

**Comment by kelseyscherer** [comment]
Lgtm.
