### ISSUE TITLE
High severity vulnerability affecting this repo

### ISSUE THREAD

**Issue by benmag1** [voxmedia/autotune#389]
Hi there, 

We noticed that your repo has a high severity vulnerability: 
* [Command Injection](https://snyk.io/vuln/npm:shell-quote:20160621?utm_source=gh_issue)
* Affected package: shell-quote<=1.6.0

[Here is the test report for this repo](https://snyk.io/test/github/voxmedia/autotune?utm_source=gh_issue). 
If you’d like to fix this vulnerability, Snyk lets you generate a pull request that recommends the best upgrade path - there’s a link to fix this vulnerability on the test report. 

Stay secure :-)

Ben from the Snyk team

**Comment by jm** [comment]
Hi @benmag1!  We don't actually use any node.js components in any public-facing/server capacity (and I don't think we even actually use `outpipe` or `shell-quote` at all even though they're in our shrinkwrap), so this vulnerability isn't actually a vulnerability for us.

Thanks!
