### ISSUE TITLE
[question] Preview urls?

### ISSUE THREAD

**Issue by pardo-bsso** [voxmedia/autotune#392]
Hello again,

I'm sure I'm missing something obvious but using latest master of Autotune and Vox-Slider the live preview tries to load a route like

    /media/vox-slider/81678ae1090187ff3d4f3454764c1b0aa5a74ed5/preview?[rest of the params]

that fails with a 404 error.

I am not managing to understand what I did wrong, I'd appreciate any hints on this.

Thanks

**Comment by ryanmark** [comment]
Hmmm. Are you storing previews on s3 or on the local filesystem?

**Comment by pardo-bsso** [comment]
> Hmmm. Are you storing previews on s3 or on the local filesystem?

We are using local filesystem.

This happens both using the development server or unicorn and our soon to be production server with passenger+nginx

**Comment by pardo-bsso** [comment]
I'm closing this, I probably touched something and broke it because it's working as intended now with the blueprints made by Vox.
