### ISSUE TITLE
[documentation] Minor changes when running under rvm

### ISSUE THREAD

**Issue by pardo-bsso** [voxmedia/autotune#393]
Hi all,

when running Autotune and Resque under rvm we had to add this to config/initializers/autotune.rb:

```ruby
  if ENV['GEM_PATH']
    conf.setup_environment['GEM_PATH'] = ENV['GEM_PATH']
    conf.build_environment['GEM_PATH'] = ENV['GEM_PATH']
  end

  if ENV['GEM_HOME']
    conf.setup_environment['GEM_HOME'] = ENV['GEM_HOME']
    conf.build_environment['GEM_HOME'] = ENV['GEM_HOME']
  end
```

because otherwise all the build/upgrade jobs for Middleman blueprints failed to find the gems under rvm.
Perhaps something like this could be added to the setup guide.

**Comment by pardo-bsso** [comment]
I see that I can edit the wiki, is it ok if I do this myself?

Thanks.

**Comment by ryanmark** [comment]
So I would think that this would interfere with the bundle for individual blueprints. Do your blueprints have their own Gemfiles?

**Comment by pardo-bsso** [comment]
On 19 December 2016 at 17:14, Ryan Mark <notifications@github.com> wrote:
>
> So I would think that this would interfere with the bundle for individual blueprints. Do your blueprints have their own Gemfiles?

No, we are trying (almost there) to make ours using gulp and other
nodejs based tools.
Without that change the autotune-image-slider and wtf engine would not
build, failing with this message:

/path/to/autotune/working/blueprints/vox-slider $ bundle install
--path .bundle --deployment
/home/pardo/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/dependency.rb:315:in
`to_specs': Could not find 'bundler' (>= 0) among 14 total gem(s)
(Gem::LoadError) Checked in
'GEM_PATH=/home/pardo/.gem/ruby/2.2.0:/home/pardo/.rvm/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0',
execute `gem env` for more information from
/home/pardo/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/dependency.rb:324:in
`to_spec' from /home/pardo/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:64:in
`gem' from /home/pardo/.rvm/gems/ruby-2.2.2/bin/bundle:22:in `<main>'
from /home/pardo/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in
`eval' from /home/pardo/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in
`<main>'

I'm not yet savvy enough with Ruby in order to assert that doing this
will not pose a problem to other blueprints.

**Comment by ryanmark** [comment]
So feel free to add this to the wiki, but add a caveat that this has only been tested with the blueprints you mentioned and might cause problems for others.

**Comment by pardo-bsso** [comment]
> So feel free to add this to the wiki, but add a caveat that this has only been tested with the blueprints you mentioned and might cause problems for others.

Done, thanks!
