### ISSUE TITLE
[question] Layout customization (Autotune is always prepended to body)

### ISSUE THREAD

**Issue by pardo-bsso** [voxmedia/autotune#395]
Hello again,

In https://github.com/voxmedia/autotune/blob/master/app/views/layouts/autotune/application.html.erb#L17 we have:

```html
<%=render 'autotune/body_top' %>
<%= yield %>
<%=render 'autotune/body_bottom' %>
```

However in https://github.com/voxmedia/autotune/blob/master/appjs/app.js#L94

```javascript
 $('body').prepend(view.$el);
```

And if we try to add content into body_top that would still move the application above it.
Is there any reason to not do something like

```html
<%=render 'autotune/body_top' %>
<div id="autotune-main-body">
  <%= yield %>
</div>
<%=render 'autotune/body_bottom' %>
```

```javascript
 $('#autotune-main-body').prepend(view.$el);
```

Thanks.

**Comment by ryanmark** [comment]
That sounds totally fine
