### ISSUE TITLE
Figure out alternate method for displaying blueprint thumbnail

### ISSUE THREAD

**Issue by ryanmark** [voxmedia/autotune#76]
Currently we serve the thumbnail image from disk through rails. There is no guarantee that the thumbnail file will be available to rails. We'll need to stash the thumbnail in s3, in the db or serve it from github or something.

**Comment by caseymm** [comment]
Have added a temporary fix for displaying the thumbnail if the repo has  `config` and provides a default image if it does not. Still need to set up stash on s3.
