### ISSUE TITLE
Documentation for creating a blueprint

### ISSUE THREAD

**Issue by ryanmark** [voxmedia/autotune#77]
Documentation should contain the following
- [x] Files required for a repo to be a blueprint
- [x] Info on configuring `autotune-config.json`
- [x] Info on `autotune-build`
- [x] A step-step guide to writing a sample blueprint

**Comment by kavyasukumar** [comment]
Blueprint creation documentation is here https://github.com/voxmedia/autotune/wiki/How-to-create-a-blueprint
